In [1]:
import quandl as qd

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=qd.get("WIKI/AAPL")

In [4]:
df.head()

Open   High    Low  Close     Volume  Ex-Dividend  Split Ratio  \
Date                                                                          
1980-12-12  28.75  28.87  28.75  28.75  2093900.0          0.0          1.0   
1980-12-15  27.38  27.38  27.25  27.25   785200.0          0.0          1.0   
1980-12-16  25.37  25.37  25.25  25.25   472000.0          0.0          1.0   
1980-12-17  25.87  26.00  25.87  25.87   385900.0          0.0          1.0   
1980-12-18  26.63  26.75  26.63  26.63   327900.0          0.0          1.0   

            Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume  
Date                                                                 
1980-12-12   0.422706   0.424470  0.422706    0.422706  117258400.0  
1980-12-15   0.402563   0.402563  0.400652    0.400652   43971200.0  
1980-12-16   0.373010   0.373010  0.371246    0.371246   26432000.0  
1980-12-17   0.380362   0.382273  0.380362    0.380362   21610400.0  
1980-12-18   0.391536   0.393300  0.391536    0.391536   18362400.0

In [5]:
df.tail()

Open    High     Low    Close      Volume  Ex-Dividend  \
Date                                                                   
2018-03-21  175.04  175.09  171.26  171.270  35247358.0          0.0   
2018-03-22  170.00  172.68  168.60  168.845  41051076.0          0.0   
2018-03-23  168.39  169.92  164.94  164.940  40248954.0          0.0   
2018-03-26  168.07  173.10  166.44  172.770  36272617.0          0.0   
2018-03-27  173.68  175.15  166.92  168.340  38962839.0          0.0   

            Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  \
Date                                                                  
2018-03-21          1.0     175.04     175.09    171.26     171.270   
2018-03-22          1.0     170.00     172.68    168.60     168.845   
2018-03-23          1.0     168.39     169.92    164.94     164.940   
2018-03-26          1.0     168.07     173.10    166.44     172.770   
2018-03-27          1.0     173.68     175.15    166.92     168.340   

            Adj. Volume  
Date                     
2018-03-21   35247358.0  
2018-03-22   41051076.0  
2018-03-23   40248954.0  
2018-03-26   36272617.0  
2018-03-27   38962839.0

In [6]:
df.shape

(9400, 12)

### Adding 2 new Columns 

In [7]:
df['HL_PCT'] = (df['Adj. High']-df['Adj. Low'])/df['Adj. Close'] * 100.0
df['PCT_change'] = (df['Adj. Close']-df['Adj. Open'])/df['Adj. Open'] * 100.0

In [8]:
df.head()

Open   High    Low  Close     Volume  Ex-Dividend  Split Ratio  \
Date                                                                          
1980-12-12  28.75  28.87  28.75  28.75  2093900.0          0.0          1.0   
1980-12-15  27.38  27.38  27.25  27.25   785200.0          0.0          1.0   
1980-12-16  25.37  25.37  25.25  25.25   472000.0          0.0          1.0   
1980-12-17  25.87  26.00  25.87  25.87   385900.0          0.0          1.0   
1980-12-18  26.63  26.75  26.63  26.63   327900.0          0.0          1.0   

            Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume    HL_PCT  \
Date                                                                            
1980-12-12   0.422706   0.424470  0.422706    0.422706  117258400.0  0.417391   
1980-12-15   0.402563   0.402563  0.400652    0.400652   43971200.0  0.477064   
1980-12-16   0.373010   0.373010  0.371246    0.371246   26432000.0  0.475248   
1980-12-17   0.380362   0.382273  0.380362    0.380362   21610400.0  0.502513   
1980-12-18   0.391536   0.393300  0.391536    0.391536   18362400.0  0.450620   

            PCT_change  
Date                    
1980-12-12    0.000000  
1980-12-15   -0.474799  
1980-12-16   -0.473000  
1980-12-17    0.000000  
1980-12-18    0.000000

In [9]:
df.shape

(9400, 14)

### Datafram of Features important for prediction 

In [10]:
dg = df[['Adj. Close','PCT_change','HL_PCT']] 
dg.head()

Adj. Close  PCT_change    HL_PCT
Date                                        
1980-12-12    0.422706    0.000000  0.417391
1980-12-15    0.400652   -0.474799  0.477064
1980-12-16    0.371246   -0.473000  0.475248
1980-12-17    0.380362    0.000000  0.502513
1980-12-18    0.391536    0.000000  0.450620

In [11]:
#identifing the NAN values
df.isna().sum()

Open           0
High           0
Low            0
Close          0
Volume         0
Ex-Dividend    0
Split Ratio    0
Adj. Open      0
Adj. High      0
Adj. Low       0
Adj. Close     0
Adj. Volume    0
HL_PCT         0
PCT_change     0
dtype: int64

In [12]:
dg.isna().sum()

Adj. Close    0
PCT_change    0
HL_PCT        0
dtype: int64

No NaN values are present in the new dataframe

In [13]:
#for 10 days out so that we can generate prediction for every day for the next 10 days
dg['Prediction'] = dg[['Adj. Close']].shift(-10)
dg.head()

<ipython-input-13-ffa45a675545>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dg['Prediction'] = dg[['Adj. Close']].shift(-10)


Adj. Close  PCT_change    HL_PCT  Prediction
Date                                                    
1980-12-12    0.422706    0.000000  0.417391    0.529301
1980-12-15    0.400652   -0.474799  0.477064    0.516363
1980-12-16    0.371246   -0.473000  0.475248    0.501807
1980-12-17    0.380362    0.000000  0.502513    0.507247
1980-12-18    0.391536    0.000000  0.450620    0.496220

In [14]:
dg.tail()

Adj. Close  PCT_change    HL_PCT  Prediction
Date                                                    
2018-03-21     171.270   -2.153793  2.236235         NaN
2018-03-22     168.845   -0.679412  2.416417         NaN
2018-03-23     164.940   -2.048815  3.019280         NaN
2018-03-26     172.770    2.796454  3.854836         NaN
2018-03-27     168.340   -3.074620  4.888915         NaN

In [15]:
#dropingthe last 10 records(rows) havimg NaN values
dg = dg.dropna(axis=0)

In [16]:
dg.tail()

Adj. Close  PCT_change    HL_PCT  Prediction
Date                                                    
2018-03-07      175.03    0.051446  0.902702     171.270
2018-03-08      176.94    0.832004  1.158585     168.845
2018-03-09      179.98    1.135087  1.450161     164.940
2018-03-12      181.72    0.793167  1.199648     172.770
2018-03-13      179.97   -1.434909  2.367061     168.340

In [17]:
import math
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

***Dividing the dataframe into two numpy arrays***

In [18]:
x = np.array(dg.drop(['Prediction'],1))
y = np.array(dg['Prediction'])
x

array([[  0.42270592,   0.        ,   0.4173913 ],
       [  0.40065169,  -0.47479912,   0.47706422],
       [  0.37124607,  -0.47299961,   0.47524752],
       ...,
       [179.98      ,   1.13508654,   1.45016113],
       [181.72      ,   0.79316656,   1.19964781],
       [179.97      ,  -1.43490881,   2.36706118]])

In [19]:
y

array([  0.52930132,   0.51636284,   0.50180706, ..., 164.94      ,
       172.77      , 168.34      ])

In [20]:
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

***scaling of data***

In [22]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [24]:
X_scaler = scaler.transform(x)
X_scaler


array([[-0.53836004,  0.00931253, -1.2836082 ],
       [-0.53892587, -0.18920813, -1.2565758 ],
       [-0.53968031, -0.18845572, -1.25739878],
       ...,
       [ 4.06842606,  0.48390929, -0.8157536 ],
       [ 4.11306812,  0.34094741, -0.92923853],
       [ 4.0681695 , -0.59064443, -0.40038911]])

In [25]:
print('Mean: ',X_scaler.mean(axis=0))
print('STD: ',X_scaler.std(axis=0))

Mean:  [9.68577957e-17 5.29691070e-18 7.26433468e-17]
STD:  [1. 1. 1.]


***spliting data into train and test data***

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 1)

In [28]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [29]:
print('Training Score: ', round(lr.score(x_train,y_train)*100,2))
print('Testing Score: ', round(lr.score(x_test,y_test)*100,2))

Training Score:  99.7
Testing Score:  99.76


In [30]:
confi = lr.score(x_train,y_train)
print('Confi(Training Score): ',confi*100)
confi = lr.score(x_test,y_test)
print('Confi(Test Score): ',confi*100)

Confi(Training Score):  99.70280806013974
Confi(Test Score):  99.75696006426031


***model prediction***

In [31]:
y_pred = lr.predict(x_test)
y_pred

array([ 1.93182646, 49.17742762,  1.10956025, ...,  1.08431282,
        1.66298035,  1.30262491])

***accuracy of the model***

In [32]:
acc=metrics.r2_score(y_test,y_pred)
print("Accuracy of Model: ",round(acc*100,2),'%')

Accuracy of Model:  99.76 %


***comparing actual vs predicted***

In [33]:
prediction_dg = pd.DataFrame({ 'Actual Price': y_test, 'Predicted Price': y_pred})  
prediction_dg.head()

Actual Price  Predicted Price
0      1.671245         1.931826
1     53.134088        49.177428
2      0.915662         1.109560
3      0.216867         0.318050
4      1.359289         1.513011

***model evaluation***

In [34]:
print('Mean Squared Error:',round(metrics.mean_squared_error(y_test,y_pred),2))

Mean Squared Error: 3.57


In [35]:
print('Mean Squared Error: ',mean_squared_error(y_test,y_pred))
print('R squared/coefficient of determination: ',r2_score(y_test,y_pred))
print('Root Mean Squared Error:',round(np.sqrt(metrics.mean_squared_error(y_test,y_pred)),2))

Mean Squared Error:  3.5707075063700247
R squared/coefficient of determination:  0.9975696006426031
Root Mean Squared Error: 1.89


***function for price prediction***

In [36]:
def Predictprice(days):
    
    #creating a variable shows the prediction days
    import quandl as qd
    import pandas as pd
    pd.options.mode.chained_assignment= None 
    default='warn'
    import numpy as np
    from sklearn import metrics
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
    import math
    from sklearn.linear_model import LinearRegression
    from sklearn.model_selection import train_test_split
    n=days
    df=qd.get("WIKI/AAPL")
    df['HL_PCT'] = (df['Adj. High']-df['Adj. Low'])/df['Adj. Close'] * 100.0
    df['PCT_change'] = (df['Adj. Close']-df['Adj. Open'])/df['Adj. Open'] * 100.0
    dg = df[['Adj. Close','PCT_change','HL_PCT']]
    dg['Prediction'] = dg[['Adj. Close']].shift(-n)
    
    # Convert the dataframe to a numpy array
    X = np.array(dg.drop(['Prediction'],1))
    y = np.array(dg['Prediction'])
    
    #remove n values from each X and y
    X = X[:-n]
    y = y[:-n]
    
    #Spliting data into Train and test data
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 1)
    lr = LinearRegression()
    lr.fit(x_train, y_train)
    
    print('Training Score: ', round(lr.score(x_train,y_train)*100,2))
    print('Testing Score: ', round(lr.score(x_test,y_test)*100,2))
    
    confi = lr.score(x_train,y_train)
    print('Confi(Training Score): ',confi*100)
    confi = lr.score(x_test,y_test)
    print('Confi(Test Score): ',confi*100)
    
    y_pred = lr.predict(x_test)
    y_pred
    
    acc=metrics.r2_score(y_test,y_pred)
    print("Accuracy of Model: ",round(acc*100,2),'%')
    
    # Set x_forecast equal to the last 10 rows of the original data set from Adj. Close column
    x_forecast = np.array(dg.drop(['Prediction'],1))[-n:]
    
    # Print linear regression model predictions for the next 'n' days
    lr_prediction = lr.predict(x_forecast)
    print('Prediction for next {} day price:\n\n{}'.format(n,lr_prediction))

In [37]:
#Predicted price for next 1 days
Predictprice(1)

Training Score:  99.97
Testing Score:  99.97
Confi(Training Score):  99.97043483489144
Confi(Test Score):  99.97467540711706
Accuracy of Model:  99.97 %
Prediction for next 1 day price:

[168.47072664]


In [38]:
#Predicted price for next 8 days
Predictprice(8)

Training Score:  99.77
Testing Score:  99.78
Confi(Training Score):  99.76602484995848
Confi(Test Score):  99.78356048851155
Accuracy of Model:  99.78 %
Prediction for next 8 day price:

[178.99582059 176.25931392 176.19775788 172.21507892 169.76639488
 165.84705157 173.67938081 169.26061447]


In [39]:
#Predicted price for next 10 days
Predictprice(10)

Training Score:  99.7
Testing Score:  99.76
Confi(Training Score):  99.70280806013974
Confi(Test Score):  99.75696006426031
Accuracy of Model:  99.76 %
Prediction for next 10 day price:

[179.74025927 179.95450994 179.3241609  176.57163724 176.52243684
 172.51331647 170.06908238 166.13111583 174.00517502 169.53558641]
